global:
  scrape_interval: 10s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090
- job_name: 'metrics-collector'
  static_configs:
  - targets:
    - 'metrics-collector:8006'
  metric_relabel_configs:
  - source_labels: ['__name__']
    regex: '.*_created'
    action: drop
